api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from api.views import ProductApiView, ProductDetailApiView
app_name = "api"
urlpatterns = [
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('', ProductApiView.as_view(), name='product'),
    path('<int:product_id>', ProductDetailApiView.as_view(), name='detail'),
]

cosinus/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include
from .views import Index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name='index'),
    path('users/', include('users.urls')),
    path('product/', include('product.urls')),
    path('api/', include('api.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from product.views import ProductView, ProductDetailView, ProductEditView, ConfirmDeleteProductView, DeleteProductView,AddProductView

app_name = "product"
urlpatterns = [
	path('', ProductView.as_view(), name='product'),
	path('add', AddProductView.as_view(), name='add-product'),
	path('<int:product_id>', ProductDetailView.as_view(), name='detail'),
	path('<int:product_id>/edit', ProductEditView.as_view(), name='edit-product'),

	path(
		"<int:product_id>/delete/confirm/",
		ConfirmDeleteProductView.as_view(),
		name="confirm-delete-product"
	),
	path(
		"<int:product_id>/delete/",
		DeleteProductView.as_view(),
		name="delete-product"
	),

]

product/models.py
from django.db import models

from users.models import CostumeUser


class ProductStatus(models.Model):
	name = models.CharField(max_length=20)

	def __str__(self):
		return f"{self.name}"


class Product(models.Model):
	user = models.ForeignKey(CostumeUser, on_delete=models.CASCADE)
	name = models.CharField(max_length=100)
	image = models.ImageField(default="product-placeholder.png")
	price = models.IntegerField()
	create_time = models.DateTimeField(auto_now=True)
	update_time = models.DateTimeField(auto_now=True)
	status = models.ForeignKey(ProductStatus, on_delete=models.CASCADE)

	def __str__(self):
		return f"{self.user.first_name} {self.user.last_name} {self.name}"

product/forms.py
from django.forms import ModelForm
from product.models import Product


class ProductCreateForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price',  'status',  'image']

    # def save(self, commit=True):
    #     product = super().save(commit)
    #
    #     return product


class ProductEditForm(ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'price',  'status',  'image')

product/views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from product.models import Product
from product.forms import ProductEditForm, ProductCreateForm


def check_product(pk, user):
	try:
		room = Product.objects.get(id=pk, user=user)
		return room
	except ObjectDoesNotExist:

		return False


class ProductView(View, LoginRequiredMixin):

	def get(self, request):
		if not request.user.is_authenticated:
			return redirect('users:login')
		else:
			user = request.user
			products = Product.objects.filter(user=user)
			return render(request, 'product/list.html', {"products": products})


class AddProductView(View, LoginRequiredMixin):
	def get(self, request):
		if not request.user.is_authenticated:
			return redirect('users:login')
		else:
			create_product_form = ProductCreateForm()
			return render(request, 'product/add_product.html', {"create_product_form": create_product_form})

	def post(self, request):
		if not request.user.is_authenticated:
			return redirect('users:login')
		else:
			create_product_form = ProductCreateForm(
				data=request.POST,
				files=request.FILES
			)
			user = request.user
			if create_product_form.is_valid():
				instance = create_product_form.save(commit=False)
				instance.user = user
				instance.save()
				products = Product.objects.filter(user=user)
				return render(request, 'product/list.html', {"products": products})
			return render(request, 'product/add_product.html', {"create_product_form": create_product_form})


class ProductDetailView(View, LoginRequiredMixin):
	def get(self, request, product_id):
		if not request.user.is_authenticated:
			return redirect('users:login')
		else:
			user = request.user
			product = check_product(product_id, user)
			if not product:
				contex = {
					'error': "Bunday mahsulot topilmadi"
				}
				return render(request, "product/list.html", contex)
			return render(request, 'product/detail.html', {"product": product})


class ProductEditView(View, LoginRequiredMixin):
	def get(self, request, product_id):
		if not request.user.is_authenticated:
			return redirect('users:login')
		else:
			user = request.user
			product = check_product(product_id, user)
			if not product:
				contex = {
					'error': "Bunday mahsulot topilmadi"
				}
				return render(request, "product/list.html", contex)
			product_edit_form = ProductEditForm(instance=product)
			return render(
				request,
				"product/edit_product.html",
				{
					"product": product, "product_form": product_edit_form
				}
			)

	def post(self, request, product_id):
		if not request.user.is_authenticated:
			return redirect('users:login')
		else:
			user = request.user
			product = check_product(product_id, user)
			if not product:
				contex = {
					'error': "Bunday mahsulot topilmadi"
				}
				return render(request, "product/list.html", contex)
			product_edit_form = ProductEditForm(instance=product, data=request.POST, files=request.FILES)
			user = request.user
			if product_edit_form.is_valid():
				instance = product_edit_form.save(commit=False)
				instance.create_time = product.create_time
				instance.update_time = datetime.datetime.now()
				instance.user = user
				instance.save()
				return redirect(reverse("product:detail", kwargs={"product_id": product_id}))

			return render(request, "books/edit_review.html", {"product": product, "product_edit_form": product_edit_form})


class ConfirmDeleteProductView(LoginRequiredMixin, View):
	def get(self, request, product_id):
		if not request.user.is_authenticated:
			return redirect('users:login')
		else:
			user = request.user
			product = check_product(product_id, user)
			if not product:
				contex = {
					'error': "Bunday mahsulot topilmadi"
				}
				return render(request, "product/list.html", contex)

			return render(request, "product/confirm_delete_product.html", {"product": product})


class DeleteProductView(LoginRequiredMixin, View):
	def get(self, request, product_id):
		if not request.user.is_authenticated:
			return redirect('users:login')
		else:
			user = request.user
			product = check_product(product_id, user)
			if not product:
				contex = {
					'error': "Bunday mahsulot topilmadi"
				}
				return render(request, "product/list.html", contex)
			product.delete()
			messages.success(request, "You have successfully deleted this review")

			return redirect(reverse("product:product"))

product/templates/product/add_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Add Product {% endblock %}

{% block contend %}
    <h3>Add Product</h3>

    <div class="row mb-4">
        <div class="col-6">
            <form method="post" action="{% url 'product:add-product'%}" enctype="multipart/form-data">
                {% csrf_token %}

                {{ create_product_form | crispy }}

                <button class="btn btn-success">Save</button>
            </form>

        </div>
    </div>
{% endblock %}

product/templates/product/confirm_delete_product.html
{% extends 'base.html' %}

{% block title %} Confirm Delete Product {% endblock %}

{% block contend %}
    <h3>Are you sure you want to delete this Product?</h3>

    <p>
        <b>Book</b>: {{ product.name }}
    </p>

    <a href="{% url 'product:delete-product' product.id %}" class="btn btn-outline-danger">Yes</a>
    <a href="{% url 'product:detail' product.id %}" class="btn btn-outline-primary">No</a>
{% endblock %}

product/templates/product/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Datail page {% endblock %}


{% block contend %}
    {%if error%}
    <div class="row ">
        <div class="col-6">
            <h1>{{error}}</h1>

        </div>
    </div>
    {%else%}
    <div class="row ">
        <div class="col-4">
            <img class="cover_pic" alt="product" src="{{product.image.url}} ">

        </div>
    </div>
     <div class="row mb-3">
        <div class="col-6">
            {{ product.name }}<br><br>
            {{ product.price }}<br><br>
            {{product.create_time}}<br><br>
            {{product.update_time}}<br><br>
            {{ product.status.name }}<br><br>
        </div>
    </div>
    <a class="nav-link btn btn-info border - 5" href="{% url 'product:confirm-delete-product' product.id %}">o'chirsih</a>
    <a class="nav-link btn btn-info border - 5" href="{% url 'product:edit-product' product.id %}"> yangilash</a>
    {%endif%}

{% endblock %}

product/templates/product/edit_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Edit Product {% endblock %}

{% block contend %}
    <h3>Edit Product</h3>

    <div class="row mb-4">
        <div class="col-6">
            <form method="post" action="{% url 'product:edit-product' product.id %}" enctype="multipart/form-data">
                {% csrf_token %}

                {{ product_form | crispy }}

                <button class="btn btn-success">Save</button>
            </form>

        </div>
    </div>
{% endblock %}

product/templates/product/list.html
{% extends "base.html" %}
{% block title %} Books {% endblock %}

{% block contend%}
{% if products %}
{% for product in products %}
<div class="row mt-3">
    <div class="col-2">
        <img class="cover_pic" alt="product" src="{{product.image.url}} ">

    </div>
    <div class="col-4 ml-3">
        <a href="{% url 'product:detail' product.id %}">
            {{product.name}}<br>
        </a>

    </div>
        <div class="col-3 ml-3">
            {{product.price}}<br>
        </a>

    </div>        <div class="col-3 ml-3">
        <a href="{% url 'product:detail' product.id %}">
            {{product.status.name}}<br>
        </a>
    </div>
</div>

{% endfor %}
{%endif%}
<div class="row mt-3">
    <a href="{% url 'product:add-product'  %}"> yangi mahsulot yaratish</a>
</div>

{%endblock%}