api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from api.views import ProductApiView, ProductDetailApiView
app_name = "api"
urlpatterns = [
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('', ProductApiView.as_view(), name='product'),
    path('<int:product_id>', ProductDetailApiView.as_view(), name='detail'),
]

cosinus/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include
from .views import Index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name='index'),
    path('users/', include('users.urls')),
    path('product/', include('product.urls')),
    path('api/', include('api.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, LogoutView, ProfileView, ProfileEditView

app_name = "users"

urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('profile_edit', ProfileEditView.as_view(), name='profile_edit'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CostumeUser(AbstractUser):
	avatar = models.ImageField(default="default_photo.jpg")
	phone_number = models.CharField(max_length=13)

	def __str__(self):
		return f"{self.username} {self.last_name}"

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from users.form import UserCreateForm, UserEditForm


# Create your views here.

class RegisterView(View):

    def get(self, request):
        create_form = UserCreateForm
        contex = {
            'form': create_form
        }
        return render(request, 'users/register.html', contex)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)
        if create_form.is_valid():
            create_form.save()
            messages.info(request, 'siz ro\'yxatdan o\'tdimgiz')
            return redirect('users:login')
        else:
            contex = {
                'form': create_form
            }
            return render(request, 'users/register.html', contex)


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm
        contex = {
            'form': login_form
        }
        return render(request, 'users/login.html', contex)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, "Siz tizimga kirdingiz")
            return redirect("index")
        else:
            return render(request, 'users/login.html', {"form": login_form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        messages.info(request, "Siz tizimdan chiqtingiz")
        return redirect("index")


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        return render(request, "users/profile.html", {"user": user})


class ProfileEditView(LoginRequiredMixin, View):
    def get(self, request):
        edit_form = UserEditForm(instance=request.user)
        contex = {
            'form': edit_form
        }
        return render(request, 'users/profile_edit.html', contex)

    def post(self, request):
        edit_form = UserEditForm(
            instance=request.user,
            data=request.POST,
            files=request.FILES
        )
        if edit_form.is_valid():
            edit_form.save()
            messages.info(request, "Ma'lumotlar muofiqaiyatli yangilandi")
            return redirect('users:profile')

        return render(request, "users/profile_edit.html", {"form": edit_form})

users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} login {% endblock %}


{% block contend %}
<div class="row ml-2">
    <div class="col-4">
        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-primary">login</button>  <h6> Do you have not account? Please <a href="{% url 'users:register' %}">Registrate</a> </h6>
        </form>

    </div>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% block title %} profile {% endblock %}


{% block contend %}

<h1> Profile page</h1>
    <img class="img" src="{{user.avatar.url}}"> <br>
    <a href="{% url 'users:profile_edit' %}">  Edit </a> <br>

    {{user.username}}<br>
    {{user.first_name}} <br>
    {{user.last_name}}<br>
    {{user.email}}<br>
{% endblock %}

users/templates/users/profile_edit.html
{% extends "base.html" %}
{% block title %} register {% endblock %}


{% block contend %}


<form method="post" action="{% url 'users:profile_edit' %}" enctype="multipart/form-data">
    {% csrf_token   %}

    {{ form.as_p }}

    <button type="submit"> Yangilash </button>
</form>

{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} register {% endblock %}


{% block contend %}

<div class="row ml-2">
    <div class="col-6">
        <form method="post" action="{% url 'users:register' %}">
            {% csrf_token   %}

             {{form|crispy}}

            <button type="submit" class="btn btn-primary">  yaratish </button>

        </form>
    </div>
</div>
{% endblock %}