api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from api.views import ProductApiView, ProductDetailApiView
app_name = "api"
urlpatterns = [
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('', ProductApiView.as_view(), name='product'),
    path('<int:product_id>', ProductDetailApiView.as_view(), name='detail'),
]

cosinus/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include
from .views import Index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name='index'),
    path('users/', include('users.urls')),
    path('product/', include('product.urls')),
    path('api/', include('api.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, LogoutView, ProfileView, ProfileEditView

app_name = "users"

urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('profile_edit', ProfileEditView.as_view(), name='profile_edit'),

]

templates/base.html
{% load static %}
{% url 'index' as home_page_url %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%} Asosiy sahifa {% endblock %}</title>
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
  <link rel = 'stylesheet', href="{% static  'css/main.css'%}">
<!--  <link rel = 'stylesheet', href="{% static  'css/bootstrap.min.css'%}">-->
<!--  <script src="{% static  'js/bootstrap.min.js'%}">-->
</head>
<body class="mx-5">

  <nav class="navbar navbar-expand-lg navbar-light bg-primary mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href=#">Products</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link {% if request.path == home_page_url %} active {%endif%}" aria-current="page" href="{{home_page_url}}">Home</a>
          </li>
        </ul>
      </ul>
      <div class="d-flex">
        {% if request.user.is_authenticated%}
          <div class="nav-item my-2 my-lg-0 " >
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link btn btn-info border - 5" href="{% url 'users:profile' %}">
                  {{request.user.username}}
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link btn btn-danger" href="{% url 'users:logout' %}" >
                  Logout
                </a>
              </li>
              </ul>
          </div>
        {%else%}
            <a class="btn btn-primary" href="{% url 'users:login'%}">login</a>
          <a class="btn btn-info" href="{% url 'users:register' %}">Registration</a>
        {%endif%}

      </div>
    </div>
</nav>
  <div class="container">

      {% if messages %}
            <div class="mt-4">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>

    {% endif %}
  {% block contend %}

  {% endblock %}


  </div>




</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}


{% block contend %}
<h1>Reviews</h1>

<div class="container posts-content row">
    <div class="col">
        {% for review in reviews %}
        <div class="row">
            <div class="col-lg-6">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="media mb-3">
                            <img src="{{review.user.user_photo.url}}" class="d-block ui-w-40 rounded-circle" alt="">
                            <div class="media-body ml-3">
                                <b>{{review.user.username}}</b> rate is {{review.stars_given}} stars
                                <div class="text-muted small">{{review.created_date|date:"M d, Y"}}</div>
                            </div>
                        </div>
                        <p>
                            {{review.comment|truncatechars:200}}
                        </p>
                        <img src="{{review.book.cover_photo.url}}" class="cover1_pic center " alt="book">


                    </div>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
    <div class="col-6">
        <div class="row">
            <h1> Books genres</h1>
            {%for genre in genres%}
            <div class="row">
                <h3>{{genre.name}}</h3>
                <div class="col">
                {%for book in genre.book_set.all%}
            <div class=" d-inline p-2">
                <a href="{% url 'books:detail' book.id %}">
                <img class="like " alt="book" src="{{book.cover_photo.url}} "></a>
            </div>
                {%endfor%}
            </div>
            {%endfor%}
        </div>

    </div>
</div>


{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block contend %}
<b>
    <h3> Bu platforma orqali foydalanuvchilar mahsulotlar kiritishi mumkin
    </h3>

</b>

<br>


{% endblock %}